config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :statuses
  root to: 'statuses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/status.rb
class Status < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


       
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/statuses_controller.rb
class StatusesController < ApplicationController
  before_action :set_status, only: [:show, :edit, :update, :destroy]

  # GET /statuses
  # GET /statuses.json
  def index
    @statuses = Status.all
  end

  # GET /statuses/1
  # GET /statuses/1.json
  def show
  end

  # GET /statuses/new
  def new
    @status = Status.new
  end

  # GET /statuses/1/edit
  def edit
  end

  # POST /statuses
  # POST /statuses.json
  def create
    @status = Status.new(status_params)

    respond_to do |format|
      if @status.save
        format.html { redirect_to @status, notice: 'Status was successfully created.' }
        format.json { render :show, status: :created, location: @status }
      else
        format.html { render :new }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /statuses/1
  # PATCH/PUT /statuses/1.json
  def update
    respond_to do |format|
      if @status.update(status_params)
        format.html { redirect_to @status, notice: 'Status was successfully updated.' }
        format.json { render :show, status: :ok, location: @status }
      else
        format.html { render :edit }
        format.json { render json: @status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /statuses/1
  # DELETE /statuses/1.json
  def destroy
    @status.destroy
    respond_to do |format|
      format.html { redirect_to statuses_url, notice: 'Status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_status
      @status = Status.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def status_params
      params.require(:status).permit(:name, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/statuses_helper.rb
module StatusesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Treebook</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Gp Bootstrap Template</title>

    <!-- Bootstrap -->
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="css/font-awesome.min.css">
    <link href="css/animate.min.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
    <!-- =======================================================
      Theme Name: Gp
      Theme URL: https://bootstrapmade.com/gp-free-multipurpose-html-bootstrap-templat/
      Author: BootstrapMade
      Author URL: https://bootstrapmade.com
    ======================================================= -->

  </head>

  <body class="homepage">
    <header id="header">
      <nav class="navbar navbar-fixed-top" role="banner">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                          <span class="sr-only">Toggle navigation</span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                          <span class="icon-bar"></span>
                      </button>
            <a class="navbar-brand" href="index.html">T.O.C.</a>
          </div>

          <div class="collapse navbar-collapse navbar-right">
            <ul class="nav navbar-nav">
              <li class="active"><a href="index.html">Home</a></li>
              <li><a href="about-us.html">About Us</a></li>
              <li><a href="services.html">Services</a></li>
              <li><a href="portfolio.html">Portfolio</a></li>
              <li><a href="blog.html">Blog</a></li>
              <li><a href="contact-us.html">Contact</a></li>
            </ul>
          </div>
        </div>
        <!--/.container-->
      </nav>
      <!--/nav-->

    </header>
    <!--/header-->

    <div class="slider">
      <div class="container">
        <div id="about-slider">
          <div id="carousel-slider" class="carousel slide" data-ride="carousel">
            <!-- Indicators -->
            <ol class="carousel-indicators visible-xs">
              <li data-target="#carousel-slider" data-slide-to="0" class="active"></li>
              <li data-target="#carousel-slider" data-slide-to="1"></li>
              <li data-target="#carousel-slider" data-slide-to="2"></li>
            </ol>

            <div class="carousel-inner">
              <div class="item active">
                <img src="images/slider_one.jpg" class="img-responsive" alt="">
              </div>
              <div class="item">
                <img src="images/slider_one.jpg" class="img-responsive" alt="">
              </div>
              <div class="item">
                <img src="images/slider_one.jpg" class="img-responsive" alt="">
              </div>
            </div>

            <a class="left carousel-control hidden-xs" href="#carousel-slider" data-slide="prev">
  						<i class="fa fa-angle-left"></i>
  					</a>

            <a class=" right carousel-control hidden-xs" href="#carousel-slider" data-slide="next">
  						<i class="fa fa-angle-right"></i>
  					</a>
          </div>
          <!--/#carousel-slider-->
        </div>
        <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
      <%= yield %>
      </div>
    </div>

    <section id="feature">
      <div class="container">
        <div class="center wow fadeInDown">
          <h2>UNDER CONSTRUCION</h2>
          <p class="lead">This site is under constrution. <br> Come back and see us soon.</p>
        </div>

        <div class="row">
          <div class="features">
            <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
              <div class="feature-wrap">
                <i class="fa fa-laptop"></i>
                <h2>@theoccultcorner</h2>
                <h3>follow upvoe resteem.</h3>
              </div>
            </div>
            <!--/.col-md-4-->

            <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
              <div class="feature-wrap">
                <i class="fa fa-comments"></i>
                <h2>@theoccultcorner</h2>
                <h3>follow upvote resteem</h3>
              </div>
            </div>
            <!--/.col-md-4-->

            <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
              <div class="feature-wrap">
                <i class="fa fa-cloud-download"></i>
                <h2>@theoccultcorner</h2>
                <h3>follow upvote resteem</h3>
              </div>
            </div>
            <!--/.col-md-4-->

            <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
              <div class="feature-wrap">
                <i class="fa fa-leaf"></i>
                <h2>@theoccultcorner</h2>
                <h3>follow upvote resteem</h3>
              </div>
            </div>
            <!--/.col-md-4-->

            <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
              <div class="feature-wrap">
                <i class="fa fa-cogs"></i>
                <h2>@theoccultcorner</h2>
                <h3>follow upvote resteem</h3>
              </div>
            </div>
            <!--/.col-md-4-->

            <div class="col-md-4 col-sm-6 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
              <div class="feature-wrap">
                <i class="fa fa-heart"></i>
                <h2>@theoccultcorner</h2>
                <h3>follow upvote resteem</h3>
              </div>
            </div>
            <!--/.col-md-4-->
          </div>
          <!--/.services-->
        </div>
        <!--/.row-->
      </div>
      <!--/.container-->
    </section>
    <!--/#feature-->

        <!--/.row-->
      </div>
      <!--/.container-->
    </section>

    <!--/#middle-->

    <section id="bottom">
      <div class="container wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
        <div class="row">
          <div class="col-md-3 col-sm-6">
            <div class="widget">
              <h3>Company</h3>
              <ul>
                <li><a href="#">About us</a></li>
                <li><a href="#">We are hiring</a></li>
                <li><a href="#">Meet the team</a></li>
                <li><a href="#">Copyright</a></li>
              </ul>
            </div>
          </div>
          <!--/.col-md-3-->

          <div class="col-md-3 col-sm-6">
            <div class="widget">
              <h3>Support</h3>
              <ul>
                <li><a href="#">Faq</a></li>
                <li><a href="#">Blog</a></li>
                <li><a href="#">Forum</a></li>
                <li><a href="#">Documentation</a></li>
              </ul>
            </div>
          </div>
          <!--/.col-md-3-->

          <div class="col-md-3 col-sm-6">
            <div class="widget">
              <h3>Developers</h3>
              <ul>
                <li><a href="#">Web Development</a></li>
                <li><a href="#">SEO Marketing</a></li>
                <li><a href="#">Theme</a></li>
                <li><a href="#">Development</a></li>
              </ul>
            </div>
          </div>
          <!--/.col-md-3-->

          <div class="col-md-3 col-sm-6">
            <div class="widget">
              <h3>Our Partners</h3>
              <ul>
                <li><a href="#">Adipisicing Elit</a></li>
                <li><a href="#">Eiusmod</a></li>
                <li><a href="#">Tempor</a></li>
                <li><a href="#">Veniam</a></li>
              </ul>
            </div>
          </div>
          <!--/.col-md-3-->
        </div>
      </div>
    </section>
    <!--/#bottom-->

    <div class="top-bar">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <div class="social">
              <ul class="social-share">
                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a href="#"><i class="fa fa-dribbble"></i></a></li>
                <li><a href="#"><i class="fa fa-skype"></i></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <!--/.container-->
    </div>
    <!--/.top-bar-->

    <footer id="footer" class="midnight-blue">
      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            &copy; Theoccultcorner All rights reserved.
            <div class="credits">
              <!--
                All the links in the footer should remain intact.
                You can delete the links only if you purchased the pro version.
                Licensing information: https://bootstrapmade.com/license/
                Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=Gp
              -->
              <a href="https://bootstrapmade.com/">site built march 11, 2018. </a> by <a href="https://bootstrapmade.com/"> The Occult Corner</a>
            </div>
          </div>
          <div class="col-sm-6">
            <ul class="pull-right">
              <li><a href="#">Home</a></li>
              <li><a href="#">About Us</a></li>
              <li><a href="#">Faq</a></li>
              <li><a href="#">Contact Us</a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <!--/#footer-->

    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/jquery.isotope.min.js"></script>
    <script src="js/wow.min.js"></script>
    <script src="js/main.js"></script>
    <div class="container">

   </div>
  </body>
</html>

app/views/statuses/_form.html.erb
<%= form_with(model: status, local: true) do |form| %>
  <% if status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(status.errors.count, "error") %> prohibited this status from being saved:</h2>

      <ul>
      <% status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :status_name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :status_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/statuses/edit.html.erb
<h1>Editing Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Show', @status %> |
<%= link_to 'Back', statuses_path %>

app/views/statuses/index.html.erb
<p id="notice"><%= notice %></p>
<div class="page-header">
<h1>all Statuses</h1>
  </div>
  <%= link_to 'POST A NEW STATUS', new_status_path, class: "btn btn-success" %>
<% @statuses.each do |status| %>
<div class="status">
  <strong><%= status.name %></strong>
        <p><%= status.content %></p>
        <div class="meta">
        <td><%= link_to time_ago_in_words(status.created_at) + " ago" , status %>
        <span class="admin">
        | <%= link_to 'Edit', edit_status_path(status) %> |
        <%= link_to 'Delete', status, method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>
    </div>
  </div>
    <% end %>
  </tbody>
</table>

<br>

app/views/statuses/new.html.erb
<h1>New Status</h1>

<%= render 'form', status: @status %>

<%= link_to 'Back', statuses_path %>

app/views/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @status.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @status.content %>
</p>

<%= link_to 'Edit', edit_status_path(@status) %> |
<%= link_to 'Back', statuses_path %>